# Generated by Django 5.2.7 on 2025-11-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookingdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_first', models.CharField(blank=True, max_length=30, null=True)),
                ('Book_last', models.CharField(blank=True, max_length=30, null=True)),
                ('Book_age', models.IntegerField(blank=True, null=True)),
                ('Book_gender', models.CharField(blank=True, max_length=30, null=True)),
                ('Book_address', models.TextField(blank=True, null=True)),
                ('Book_mobile', models.IntegerField(blank=True, max_length=30, null=True)),
                ('Book_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Book_class', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='catergorydb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Duration', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='orderdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_name', models.CharField(blank=True, max_length=30, null=True)),
                ('Order_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Order_phone', models.IntegerField(blank=True, null=True)),
                ('Order_address', models.TextField(blank=True, null=True)),
                ('Order_payment', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
