# Generated by Django 5.2.7 on 2025-11-05 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdb',
            name='Book_mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
