# Generated by Django 5.2.7 on 2025-11-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_productdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='potterydb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pottery_name', models.CharField(blank=True, max_length=30, null=True)),
                ('Pottery_category', models.CharField(blank=True, max_length=30, null=True)),
                ('Pottery_price', models.IntegerField(blank=True, null=True)),
                ('Pottery_description', models.TextField(blank=True, null=True)),
                ('Pottery_image', models.ImageField(blank=True, null=True, upload_to='Pottery Images')),
            ],
        ),
    ]
