# Generated by Django 5.2.7 on 2025-11-12 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0004_potterydb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bookingdb',
        ),
        migrations.DeleteModel(
            name='orderdb',
        ),
    ]
