# Generated by Django 5.2.7 on 2025-11-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signupdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Signup_username', models.CharField(blank=True, max_length=30, null=True)),
                ('Signup_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Signup_mobile', models.IntegerField(blank=True, null=True)),
                ('Signup_password', models.CharField(blank=True, max_length=30, null=True)),
                ('Signup_confirm', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
