# Generated by Django 5.2.7 on 2025-11-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookingdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Booking_firstname', models.CharField(blank=True, max_length=30, null=True)),
                ('Booking_lastname', models.CharField(blank=True, max_length=30, null=True)),
                ('Booking_age', models.IntegerField(blank=True, null=True)),
                ('Booking_gender', models.CharField(blank=True, max_length=30, null=True)),
                ('Booking_address', models.TextField(blank=True, null=True)),
                ('Booking_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Booking_class', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orderdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_fullname', models.CharField(blank=True, max_length=30, null=True)),
                ('Order_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Order_phone', models.IntegerField(blank=True, null=True)),
                ('Order_address', models.TextField(blank=True, null=True)),
                ('Order_payment', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
