# Generated by Django 5.2.7 on 2025-11-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_bookingdb_orderdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdb',
            name='Booking_mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
