# Generated by Django 5.2.7 on 2025-11-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_bookingdb_booking_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Singlepottery_username', models.CharField(blank=True, max_length=30, null=True)),
                ('Singlepottery_name', models.CharField(blank=True, max_length=30, null=True)),
                ('Singlepottery_price', models.IntegerField(blank=True, null=True)),
                ('Singlepottery_total', models.IntegerField(blank=True, null=True)),
                ('Singlepottery_quantity', models.CharField(blank=True, max_length=30, null=True)),
                ('Singlepottery_image', models.ImageField(blank=True, null=True, upload_to='Cart Images')),
            ],
        ),
    ]
