# Generated by Django 5.2.7 on 2025-12-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_cartdb_potteryid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkoutdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullame', models.CharField(blank=True, max_length=30, null=True)),
                ('Email', models.EmailField(blank=True, max_length=30, null=True)),
                ('Address', models.CharField(blank=True, max_length=30, null=True)),
                ('City', models.CharField(blank=True, max_length=30, null=True)),
                ('Pincode', models.CharField(blank=True, max_length=30, null=True)),
                ('Total_amount', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
